spring:
  datasource:
    url: ${DATASOURCE_JDBC_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    url: ${DATASOURCE_JDBC_URL}
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
algashop:
  integrations:
    payment:
      fastpay:
        hostname: ${FASTPAY_URL}
        private-token: ${FASTPAY_PRIVATE_TOKEN}
        webhook-url: ${FASTPAY_WEBHOOK_URL}