server:
  port: 8082
spring:
  application:
    name: billing
  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/billing
    user: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true