server:
  port: 8082
spring:
  application:
    name: billing
  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/billing
    user: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
algashop:
  integrations:
    payment:
      provider: FASTPAY
      fastpay:
        hostname: http://localhost:9995
        private-token: SSEewtC6Ps5yJLdB6SJmh1bqJXgRbCdf8ocDj2hU
        webhook-url: #usar host docker /api/v1/webhook/fastpay